export const FETCHING_SMURF = "FETCHING_SMURF";
export const ADDING_SMURF = "ADDING_SMURF";
export const DELETING_SMURF = "DELETING_SMURF";
export const UPDATING_SMURF = "UPDATING_SMURF";

export const SUCCESS_SMURFS = "SUCCESS_SMURFS";
export const ERROR_SMURFS = "ERROR_SMURFS";
