export const FETCHING = 'FETCHING'
export const CREATING = 'CREATING'
export const UPDATING = 'UPDATING'
export const DELETING = 'DELETING'
export const SUCCESS = 'SUCCESS'
export const ERROR = 'ERROR'
export const EDITING = 'EDITING'
export const CANCEL_EDIT = 'CANCEL_EDIT'
